###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm
HYDRO     =   hydro
DENSITY   =   density
ENTROPY   = noentropy
MAGNETIC  = nomagnetic
FORCING   = noforcing
SHEAR     = noshear
FOURIER   =   fourier_fftpack
POWER     =   power_spectrum
REAL_PRECISION = double
